apiVersion: v1
kind: Service
metadata:
  name: lbsvc-ajeeshregi
  namespace: ajeeshregi
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80  #service port inside cluster
    targetPort: 80 #container port
    #nodePort: 30020